source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.3'

project 'SwiftSiriWaveformView'
use_frameworks!

target 'SwiftSiriWaveformView_Example' do
  pod "SwiftSiriWaveformView", :path => "../"
end

target 'SwiftSiriWaveformView_Tests' do
  pod "SwiftSiriWaveformView", :path => "../"
end

